// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ihalee.Data;

#nullable disable

namespace ihalee.Migrations
{
    [DbContext(typeof(ihaleeDBContext))]
    partial class ihaleeDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ihalee.Models.Araba", b =>
                {
                    b.Property<int>("ArabaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArabaID"));

                    b.Property<string>("AraçTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModelYılı")
                        .HasColumnType("int");

                    b.Property<int?>("MotorHacmi")
                        .HasColumnType("int");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VitesTipi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YakıtTipi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArabaID");

                    b.ToTable("Arabalar");

                    b.HasData(
                        new
                        {
                            ArabaID = 1,
                            AraçTipi = "Sedan",
                            Marka = "Renault",
                            Model = "Megan",
                            ModelYılı = 2017,
                            MotorHacmi = 1500,
                            Renk = "Beyaz",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Dizel"
                        },
                        new
                        {
                            ArabaID = 2,
                            AraçTipi = "Sedan",
                            Marka = "Opel",
                            Model = "Astra",
                            ModelYılı = 2016,
                            MotorHacmi = 1400,
                            Renk = "Kırmızı",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Benzin"
                        },
                        new
                        {
                            ArabaID = 3,
                            AraçTipi = "Hatchback",
                            Marka = "Renault",
                            Model = "Clio",
                            ModelYılı = 2017,
                            MotorHacmi = 1500,
                            Renk = "Beyaz",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Dizel"
                        },
                        new
                        {
                            ArabaID = 4,
                            AraçTipi = "Sedan",
                            Marka = "Renault",
                            Model = "Sedan",
                            ModelYılı = 2017,
                            MotorHacmi = 1500,
                            Renk = "Siyah",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Dizel"
                        },
                        new
                        {
                            ArabaID = 5,
                            AraçTipi = "Sedan",
                            Marka = "Renault",
                            Model = "Sedan",
                            ModelYılı = 2017,
                            MotorHacmi = 1500,
                            Renk = "Turuncu",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Dizel"
                        },
                        new
                        {
                            ArabaID = 6,
                            AraçTipi = "Bus",
                            Marka = "Mercedes",
                            Model = "Kamyonet",
                            ModelYılı = 2017,
                            MotorHacmi = 1500,
                            Renk = "Sarı",
                            VitesTipi = "Otomatik",
                            YakıtTipi = "Dizel"
                        });
                });

            modelBuilder.Entity("ihalee.Models.Boyama", b =>
                {
                    b.Property<int>("BoyamaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BoyamaID"));

                    b.Property<string>("BaslamaTarihi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BoyamaNiteligi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetreKare")
                        .HasColumnType("int");

                    b.Property<string>("OdaSayisi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BoyamaID");

                    b.ToTable("Boyamalar");

                    b.HasData(
                        new
                        {
                            BoyamaID = 1,
                            BaslamaTarihi = "1 Hafta içinde",
                            BoyamaNiteligi = "Kaliteli",
                            MetreKare = 55,
                            OdaSayisi = "2+1",
                            Renk = "pembe"
                        },
                        new
                        {
                            BoyamaID = 2,
                            BaslamaTarihi = "4 Hafta içinde",
                            BoyamaNiteligi = "Normal",
                            MetreKare = 90,
                            OdaSayisi = "1+1",
                            Renk = "sarı"
                        },
                        new
                        {
                            BoyamaID = 3,
                            BaslamaTarihi = "5 Hafta içinde",
                            BoyamaNiteligi = "Karışık",
                            MetreKare = 120,
                            OdaSayisi = "1+0",
                            Renk = "yeşil"
                        },
                        new
                        {
                            BoyamaID = 4,
                            BaslamaTarihi = "6 Ay içinde",
                            BoyamaNiteligi = "Kaliteli",
                            MetreKare = 60,
                            OdaSayisi = "4+1",
                            Renk = "beyaz"
                        },
                        new
                        {
                            BoyamaID = 5,
                            BaslamaTarihi = "16 Hafta içinde",
                            BoyamaNiteligi = "Normal",
                            MetreKare = 50,
                            OdaSayisi = "3+1",
                            Renk = "mavi"
                        },
                        new
                        {
                            BoyamaID = 6,
                            BaslamaTarihi = "3 gün içinde",
                            BoyamaNiteligi = "Kaliteli",
                            MetreKare = 75,
                            OdaSayisi = "3+1",
                            Renk = "kırmızı"
                        });
                });

            modelBuilder.Entity("ihalee.Models.Buzdolabı", b =>
                {
                    b.Property<int>("BuzdolabıID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuzdolabıID"));

                    b.Property<string>("BuzlukTürü")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnerjiSınıfı")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Hacim")
                        .HasColumnType("int");

                    b.Property<int>("KapıSayısı")
                        .HasColumnType("int");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NoFrostMu")
                        .HasColumnType("bit");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BuzdolabıID");

                    b.ToTable("Buzdolapları");

                    b.HasData(
                        new
                        {
                            BuzdolabıID = 1,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 240,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 2,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 480,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 3,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 560,
                            KapıSayısı = 4,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 4,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 420,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 5,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 560,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 6,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 280,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 7,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "C",
                            Hacim = 460,
                            KapıSayısı = 3,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 8,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 260,
                            KapıSayısı = 3,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 9,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 380,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 10,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "C",
                            Hacim = 460,
                            KapıSayısı = 4,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 11,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A",
                            Hacim = 600,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 12,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 400,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 13,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 200,
                            KapıSayısı = 3,
                            Marka = "LG",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 14,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 440,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 15,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 220,
                            KapıSayısı = 2,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 16,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 480,
                            KapıSayısı = 2,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 17,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 240,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 18,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 480,
                            KapıSayısı = 1,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 19,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 540,
                            KapıSayısı = 3,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 20,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 400,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 21,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 200,
                            KapıSayısı = 3,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 22,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 360,
                            KapıSayısı = 1,
                            Marka = "LG",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 23,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 280,
                            KapıSayısı = 3,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 24,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "C",
                            Hacim = 260,
                            KapıSayısı = 3,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 25,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 260,
                            KapıSayısı = 1,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 26,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 540,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 27,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 220,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 28,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 500,
                            KapıSayısı = 1,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 29,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 560,
                            KapıSayısı = 2,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 30,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 420,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 31,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 580,
                            KapıSayısı = 3,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 32,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 280,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 33,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 340,
                            KapıSayısı = 2,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 34,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 560,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 35,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 280,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 36,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 200,
                            KapıSayısı = 3,
                            Marka = "Samsung",
                            NoFrostMu = false,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 37,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A",
                            Hacim = 540,
                            KapıSayısı = 4,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 38,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 400,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 39,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 200,
                            KapıSayısı = 4,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 40,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 320,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 41,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 320,
                            KapıSayısı = 2,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 42,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 560,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 43,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 320,
                            KapıSayısı = 2,
                            Marka = "LG",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 44,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 540,
                            KapıSayısı = 4,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 45,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 380,
                            KapıSayısı = 3,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 46,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 400,
                            KapıSayısı = 4,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 47,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 240,
                            KapıSayısı = 3,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 48,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 540,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 49,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "C",
                            Hacim = 320,
                            KapıSayısı = 4,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 50,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 340,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 51,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 380,
                            KapıSayısı = 4,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 52,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 460,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 53,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "C",
                            Hacim = 520,
                            KapıSayısı = 4,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 54,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 280,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 55,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "C",
                            Hacim = 340,
                            KapıSayısı = 4,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 56,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 540,
                            KapıSayısı = 3,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 57,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 560,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 58,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "B",
                            Hacim = 400,
                            KapıSayısı = 3,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 59,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 260,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 60,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 480,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 61,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 580,
                            KapıSayısı = 2,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 62,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 360,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 63,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 240,
                            KapıSayısı = 3,
                            Marka = "Samsung",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 64,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 380,
                            KapıSayısı = 2,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 65,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 440,
                            KapıSayısı = 4,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 66,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 540,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 67,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "C",
                            Hacim = 460,
                            KapıSayısı = 3,
                            Marka = "Beko",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 68,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 340,
                            KapıSayısı = 4,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 69,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "B",
                            Hacim = 460,
                            KapıSayısı = 3,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 70,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 300,
                            KapıSayısı = 1,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 71,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 520,
                            KapıSayısı = 2,
                            Marka = "Samsung",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 72,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 420,
                            KapıSayısı = 2,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 73,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 300,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 74,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 480,
                            KapıSayısı = 3,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 75,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "C",
                            Hacim = 500,
                            KapıSayısı = 2,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 76,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 340,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 77,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 220,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 78,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 380,
                            KapıSayısı = 2,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 79,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 480,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 80,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 240,
                            KapıSayısı = 4,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 81,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 540,
                            KapıSayısı = 4,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 82,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 520,
                            KapıSayısı = 2,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 83,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 560,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 84,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 440,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 85,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 540,
                            KapıSayısı = 3,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 86,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "C",
                            Hacim = 460,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 87,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 540,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 88,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 220,
                            KapıSayısı = 2,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 89,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 600,
                            KapıSayısı = 3,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 90,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 600,
                            KapıSayısı = 2,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 91,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 520,
                            KapıSayısı = 2,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 92,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A++",
                            Hacim = 320,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 93,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 520,
                            KapıSayısı = 3,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 94,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 240,
                            KapıSayısı = 4,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 95,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 340,
                            KapıSayısı = 3,
                            Marka = "LG",
                            NoFrostMu = false,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 96,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 560,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 97,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 300,
                            KapıSayısı = 4,
                            Marka = "Arçelik",
                            NoFrostMu = false,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 98,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A++",
                            Hacim = 600,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 99,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 300,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 100,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "B",
                            Hacim = 300,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 101,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 260,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 102,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 400,
                            KapıSayısı = 3,
                            Marka = "Vestel",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 103,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 220,
                            KapıSayısı = 1,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 104,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A",
                            Hacim = 320,
                            KapıSayısı = 4,
                            Marka = "Bosch",
                            NoFrostMu = false,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 105,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "B",
                            Hacim = 520,
                            KapıSayısı = 1,
                            Marka = "Beko",
                            NoFrostMu = true,
                            Renk = "kırmızı"
                        },
                        new
                        {
                            BuzdolabıID = 106,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A+",
                            Hacim = 240,
                            KapıSayısı = 3,
                            Marka = "Samsung",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 107,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "C",
                            Hacim = 280,
                            KapıSayısı = 1,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 108,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 440,
                            KapıSayısı = 3,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 109,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 520,
                            KapıSayısı = 1,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 110,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A",
                            Hacim = 600,
                            KapıSayısı = 2,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 111,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "B",
                            Hacim = 260,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = false,
                            Renk = "kahverengi"
                        },
                        new
                        {
                            BuzdolabıID = 112,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 480,
                            KapıSayısı = 1,
                            Marka = "Vestel",
                            NoFrostMu = false,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 113,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A+",
                            Hacim = 500,
                            KapıSayısı = 1,
                            Marka = "Bosch",
                            NoFrostMu = true,
                            Renk = "yeşil"
                        },
                        new
                        {
                            BuzdolabıID = 114,
                            BuzlukTürü = "alttan kapı",
                            EnerjiSınıfı = "A",
                            Hacim = 560,
                            KapıSayısı = 2,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        },
                        new
                        {
                            BuzdolabıID = 115,
                            BuzlukTürü = "üstten kapı",
                            EnerjiSınıfı = "B",
                            Hacim = 440,
                            KapıSayısı = 1,
                            Marka = "Samsung",
                            NoFrostMu = true,
                            Renk = "beyaz"
                        },
                        new
                        {
                            BuzdolabıID = 116,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A++",
                            Hacim = 580,
                            KapıSayısı = 2,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "siyah"
                        },
                        new
                        {
                            BuzdolabıID = 117,
                            BuzlukTürü = "dolap tipi",
                            EnerjiSınıfı = "A+",
                            Hacim = 200,
                            KapıSayısı = 1,
                            Marka = "Arçelik",
                            NoFrostMu = true,
                            Renk = "pembe"
                        },
                        new
                        {
                            BuzdolabıID = 118,
                            BuzlukTürü = "yok",
                            EnerjiSınıfı = "A",
                            Hacim = 320,
                            KapıSayısı = 4,
                            Marka = "LG",
                            NoFrostMu = true,
                            Renk = "turuncu"
                        });
                });

            modelBuilder.Entity("ihalee.Models.Renk", b =>
                {
                    b.Property<int>("RenkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RenkID"));

                    b.Property<string>("RenkAdı")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RenkID");

                    b.ToTable("Renkler");

                    b.HasData(
                        new
                        {
                            RenkID = 1,
                            RenkAdı = "Kırmızı"
                        },
                        new
                        {
                            RenkID = 2,
                            RenkAdı = "Yeşil"
                        },
                        new
                        {
                            RenkID = 3,
                            RenkAdı = "Mavi"
                        },
                        new
                        {
                            RenkID = 4,
                            RenkAdı = "Turuncu"
                        },
                        new
                        {
                            RenkID = 5,
                            RenkAdı = "Kahverengi"
                        },
                        new
                        {
                            RenkID = 6,
                            RenkAdı = "Gri"
                        },
                        new
                        {
                            RenkID = 7,
                            RenkAdı = "Beyaz"
                        },
                        new
                        {
                            RenkID = 8,
                            RenkAdı = "Sarı"
                        },
                        new
                        {
                            RenkID = 9,
                            RenkAdı = "Siyah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
